# -*- coding: utf-8 -*-
"""question-0003-usecase-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NpGmGQ2sarxtTuoLpRJso-90bvDgnejN
"""

import numpy as np
import pandas as pd

def generar_casos_ciberseguridad(n_registros=2000):
    # 1. Definir proporción de ataque (5% de los datos)
    n_ataques = int(n_registros * 0.05)
    n_normal = n_registros - n_ataques

    # 2. Generar tráfico normal (Frecuencia baja, tamaño variable)
    X_normal = np.column_stack([
        np.random.normal(30, 10, n_normal),  # Frecuencia paquetes (pps)
        np.random.normal(500, 100, n_normal) # Tamaño promedio (bytes)
    ])
    y_normal = np.zeros(n_normal)

    # 3. Generar tráfico de ataque DoS (Frecuencia altísima, tamaño pequeño/fijo)
    X_ataque = np.column_stack([
        np.random.normal(8000, 500, n_ataques), # Ráfaga masiva
        np.random.normal(64, 5, n_ataques)      # Paquetes pequeños "maliciosos"
    ])
    y_ataque = np.ones(n_ataques)

    # 4. Mezclar los datos
    X = np.vstack([X_normal, X_ataque])
    y = np.concatenate([y_normal, y_ataque])

    # Desordenar para que no estén todos los ataques al final
    indices = np.random.permutation(n_registros)
    return X[indices], y[indices]

if __name__ == "__main__":
    X_train, y_train = generar_casos_ciberseguridad(2000)
    print(f"Dataset de Red generado: {X_train.shape[0]} registros.")
    print(f"Casos de ataque detectados en la muestra: {int(sum(y_train))}")
    print("\nEjemplo de los primeros 5 registros (Frecuencia, Tamaño):")
    print(X_train[:5])

