# -*- coding: utf-8 -*-
"""question-0003-usecase-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NpGmGQ2sarxtTuoLpRJso-90bvDgnejN
"""

import numpy as np
import pandas as pd

def generar_caso_de_uso_detectar_anomalias_red(n_registros=2000):
    # 1. Definir proporción de ataque (5% de los datos)
    n_ataques = int(n_registros * 0.05)
    n_normal = n_registros - n_ataques

    # 2. Generar tráfico normal
    X_normal = np.column_stack([
        np.random.normal(30, 10, n_normal),
        np.random.normal(500, 100, n_normal)
    ])
    y_normal = np.zeros(n_normal)

    # 3. Generar tráfico de ataque DoS
    X_ataque = np.column_stack([
        np.random.normal(8000, 500, n_ataques),
        np.random.normal(64, 5, n_ataques)
    ])
    y_ataque = np.ones(n_ataques)

    # 4. Mezclar los datos
    X = np.vstack([X_normal, X_ataque])
    y = np.concatenate([y_normal, y_ataque])

    indices = np.random.permutation(n_registros)
    X_final = X[indices]
    y_final = y[indices]

    # AJUSTE PARA EL VALIDADOR:
    # El primer elemento DEBE ser un diccionario con las variables de entrada
    # El segundo elemento es la respuesta esperada (la tupla X, y)
    return {"X": X_final, "y": y_final}, (X_final, y_final)

if __name__ == "__main__":
    # Prueba de ejecución
    inputs, expected_output = generar_caso_de_uso_detectar_anomalias_red(2000)

    print(f"--- Dataset de Ciberseguridad Generado ---")
    print(f"¿Primer elemento es diccionario?: {isinstance(inputs, dict)}")
    print(f"Registros en X: {inputs['X'].shape[0]}")
    print(f"Ataques detectados: {int(sum(inputs['y']))}")

