# -*- coding: utf-8 -*-
"""question-0004-usecase-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZtU9U7UKSwvzdiTyhO_XPgQkygGnsA8e
"""

import pandas as pd
import numpy as np
import random

def generar_casos_migracion_temporal(n_registros=1200):
    municipios_data = [
        ('Apartadó', 'Antioquia', 130000, 35.5),
        ('Necoclí', 'Antioquia', 45000, 48.2),
        ('Ipiales', 'Nariño', 115000, 30.1),
        ('Tumaco', 'Nariño', 220000, 52.4),
        ('Cúcuta', 'Norte de Santander', 750000, 25.5),
        ('Quibdó', 'Chocó', 130000, 65.8),
        ('Arauca', 'Arauca', 95000, 42.3),
        ('Buenaventura', 'Valle del Cauca', 450000, 41.2)
    ]

    # Definimos los periodos de reporte para justificar las repeticiones
    periodos = ['2023-Q1', '2023-Q2', '2023-Q3', '2023-Q4', '2024-Q1', '2024-Q2']

    data = []
    for _ in range(n_registros):
        nombre, depto, pob_base, ipm_base = random.choice(municipios_data)
        periodo = random.choice(periodos) # Asignamos un momento en el tiempo

        # Variación lógica por el paso del tiempo
        poblacion = pob_base + random.randint(-500, 1500)
        ipm = round(ipm_base + random.uniform(-1.5, 1.5), 2)
        capacidad_hospitalaria = int((poblacion / 1000) * random.uniform(0.5, 1.2))

        if random.random() < 0.08:
            flujo = random.randint(3000, 10000)
        else:
            flujo = random.randint(50, 600)

        ina_calc = (flujo / 100) + (ipm * 0.6) - (capacidad_hospitalaria * 0.05)
        ina = max(5, min(100, ina_calc + random.uniform(-2, 2)))

        data.append({
            'municipio': nombre,
            'departamento': depto,
            'periodo_reporte': periodo, # <-- La clave de la distinción
            'poblacion_total': poblacion,
            'ipm': ipm,
            'capacidad_hospitalaria': capacidad_hospitalaria,
            'flujo_migratorio_recent': flujo,
            'INA': round(ina, 2)
        })

    return pd.DataFrame(data)

if __name__ == "__main__":
    df_final = generar_casos_migracion_temporal(1200)

