# -*- coding: utf-8 -*-
"""question-0002-usecase-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BgfiWbXTmgn2b7pgczaZWUoaAElkeosR
"""

import pandas as pd
import numpy as np
import random

def generar_caso_de_uso_analizar_viabilidad_tierras_raras(n_registros=1200):
    # 1. Datos reales de yacimientos estratégicos y sus elementos
    yacimientos = {
        'Mountain Pass (EE.UU.)': ['Lantano', 'Neodimio', 'Cerio'],
        'Bayan Obo (China)': ['Neodimio', 'Lantano', 'Praseodimio', 'Gadolinio'],
        'Mount Weld (Australia)': ['Neodimio', 'Praseodimio', 'Lantano'],
        'Kvanefjeld (Groenlandia)': ['Terbio', 'Disprosio', 'Lantano'],
        'Serra Verde (Brasil)': ['Neodimio', 'Praseodimio', 'Terbio']
    }

    nombres_yacimientos = list(yacimientos.keys())

    data = []
    for _ in range(n_registros):
        # Seleccionar un yacimiento al azar
        yac_nombre = random.choice(nombres_yacimientos)
        # Seleccionar un elemento que realmente se extraiga en ese yacimiento
        elemento = random.choice(yacimientos[yac_nombre])

        # Concentración en PPM (Partes por millón)
        concentracion = round(random.uniform(500.0, 45000.0), 2)

        # Costo de extracción en USD por tonelada de roca procesada
        if "China" in yac_nombre:
            costo = round(random.uniform(15.0, 40.0), 2)
        elif "EE.UU." in yac_nombre or "Australia" in yac_nombre:
            costo = round(random.uniform(45.0, 90.0), 2)
        else:
            costo = round(random.uniform(30.0, 70.0), 2)

        data.append({
            'yacimiento_id': yac_nombre,
            'elemento': elemento,
            'concentracion_ppm': concentracion,
            'costo_extraccion_usd': costo
        })

    return pd.DataFrame(data)

if __name__ == "__main__":
    # Ejecución de prueba con el nuevo nombre de función
    df_mineria = generar_caso_de_uso_analizar_viabilidad_tierras_raras(1200)

    print(f"--- Dataset de Minería Estratégica Generado ({len(df_mineria)} filas) ---")
    print(df_mineria.head(10))

    # Verificación de variedad para el estudiante
    print("\nResumen de Elementos por Yacimiento:")
    print(df_mineria.groupby('yacimiento_id')['elemento'].unique())

