# -*- coding: utf-8 -*-
"""question-0001-usecase-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EYYSn-bopiwnRrPgmV7ihWDgwGqZjLgJ
"""

import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

def generar_casos_uso(n_registros=1000):
    # 1. Cantidad de lotes para simular una finca real
    lotes = [f'LOTE_{str(i).zfill(2)}' for i in range(1, 11)] # Genera LOTE_01 al LOTE_10

    # 2. Generar datos aleatorios masivos
    data = {
        'lote_id': [random.choice(lotes) for _ in range(n_registros)],
        'humedad': [round(random.uniform(5.0, 60.0), 2) for _ in range(n_registros)],
        'ndvi': [round(random.uniform(0.1, 0.95), 2) for _ in range(n_registros)],
        'timestamp': [
            (datetime(2024, 5, 1) + timedelta(
                days=random.randint(0, 15), # Datos de una quincena
                hours=random.randint(0, 23),
                minutes=random.randint(0, 59),
                seconds=random.randint(0, 59)
            )).strftime('%Y-%m-%d %H:%M:%S')
            for _ in range(n_registros)
        ]
    }

    # 3. Crear el DataFrame
    df = pd.DataFrame(data)
    return df

# Ejecución para el estudiante
if __name__ == "__main__":
    # Generamos 1000 registros para que el reto sea significativo
    df_prueba = generar_casos_uso(1000)

    # Mostramos los primeros 10 para verificar y el tamaño total
    print(f"Dataset generado con {len(df_prueba)} registros.")
    print(df_prueba.head(10))

df_prueba.head(10)

