# -*- coding: utf-8 -*-
"""answer-0344.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x9p_9kiwJRLQXhQCjsNZea8gmWdlcu6c
"""

import pandas as pd
import numpy as np

def seleccionar_mejor_proveedor(dataset, min_pureza=95.0, descuento_local=0.15):
    # 1. Copiar el DataFrame de entrada para evitar modificar el original
    df_valid = dataset[dataset['pureza_reactivo'] >= min_pureza].copy()

    # 2. Aplicar descuento logístico local a los proveedores ubicados en Colombia
    df_valid['envio_final'] = np.where(
        df_valid['pais_origen'] == 'Colombia',
        df_valid['costo_envio_usd'] * (1 - descuento_local),
        df_valid['costo_envio_usd']
    )

    # 3. Calcular el Factor de Cercanía (FC) empleando base logarítmica de Numpy
    df_valid['FC'] = 1 + np.log10(df_valid['distancia_km'] + 1)

    # 4. Obtener el costo total ajustado por distancia
    df_valid['costo_total_ajustado'] = (df_valid['precio_unitario_usd'] + df_valid['envio_final']) * df_valid['FC']

    # 5. Calcular el Índice de Viabilidad (IV) de acuerdo con la fórmula exacta del generador
    df_valid['IV'] = (df_valid['pureza_reactivo'] * 10) / df_valid['costo_total_ajustado']

    # 6. Identificar el ID del proveedor que maximiza la viabilidad
    mejor_id = df_valid.loc[df_valid['IV'].idxmax(), 'id_proveedor']

    # 7. Construir y estructurar el diccionario de salida esperado
    output = {
        'mejor_proveedor_id': mejor_id,
        'n_proveedores_aptos': int(len(df_valid)),
        'promedio_pureza_apta': float(df_valid['pureza_reactivo'].mean())
    }

    return output