# -*- coding: utf-8 -*-
"""answer-0116.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JBu895tVeZ6wQO15Hy7EWW8_rmgiOHma
"""

import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

def segmentacion_comportamental(df, n_clusters, random_state):
    # 1. Copiar el DataFrame para proteger los datos originales
    df_copy = df.copy()

    # 2. Seleccionar únicamente las columnas de tipo numérico
    numerics = df_copy.select_dtypes(include=[np.number])

    # 3. Imputar los valores faltantes (NaN) utilizando el promedio (mean)
    imputer = SimpleImputer(strategy='mean')
    imputed_data = imputer.fit_transform(numerics)

    # 4. Escalar los datos imputados con StandardScaler
    scaler = StandardScaler()
    scaled_data = scaler.fit_transform(imputed_data)

    # 5. Instanciar y entrenar el modelo KMeans con los hiperparámetros del generador
    kmeans = KMeans(n_clusters=n_clusters, random_state=random_state, n_init=10)
    kmeans.fit(scaled_data)

    # 6. Retornar el array de numpy con las etiquetas numéricas asignadas
    return kmeans.labels_