# -*- coding: utf-8 -*-
"""answer-0031.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cM1OXoW9JzTHABXdeN8pnAqnMcIr90LE
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

def codificar_y_dividir(df, target_col, test_size):
    # 1. Separar características (X) y la columna objetivo (y) como array
    X = df.drop(columns=[target_col])
    y = df[target_col].values

    # 2. Aislar las columnas numéricas originales
    X_num = X.select_dtypes(include=[np.number]).values

    # 3. Inicializar OneHotEncoder con el parámetro exacto del generador y transformar categóricas
    ohe = OneHotEncoder(sparse_output=False)
    X_cat = ohe.fit_transform(X.select_dtypes(include=["object"]))

    # 4. Concatenar horizontalmente colocando primero las categóricas y luego las numéricas
    X_final = np.hstack([X_cat, X_num])

    # 5. Dividir el dataset en conjuntos de entrenamiento y prueba usando el random_state solicitado
    X_train, X_test, y_train, y_test = train_test_split(
        X_final,
        y,
        test_size=test_size,
        random_state=42
    )

    # Devuelve la tupla con los cuatro conjuntos ordenados
    return X_train, X_test, y_train, y_test