# -*- coding: utf-8 -*-
"""answer-0101.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kR6sgtw_PQoyf8SHud-c3V6vCyqg-QU2
"""

import pandas as pd
import numpy as np

def analizar_cohorte_compras(df, fecha_col, cliente_col, venta_col):
    # 1. Copiar DataFrame y convertir columna a datetime y extraer 'mes_compra'
    df_copy = df.copy()
    df_copy[fecha_col] = pd.to_datetime(df_copy[fecha_col])
    df_copy['mes_compra'] = df_copy[fecha_col].dt.to_period('M').astype(str)

    # 2. Determinar el mes de la primera compra (cohorte) para cada cliente
    primera_compra = df_copy.groupby(cliente_col)['mes_compra'].min().reset_index()
    primera_compra.columns = [cliente_col, 'cohorte']

    # Unir para asociar cada registro con la cohorte de su cliente correspondiente
    df_cohorte = df_copy.merge(primera_compra, on=cliente_col)

    # 3. Calcular el número de meses transcurridos desde la primera compra
    df_cohorte['mes_cohorte'] = (df_cohorte[fecha_col].dt.to_period('M') -
                                  pd.PeriodIndex(df_cohorte['cohorte'], freq='M')).apply(lambda x: x.n)

    # Conteo de clientes únicos por cohorte y mes transcurrido
    cohorte_counts = df_cohorte.groupby(['cohorte', 'mes_cohorte'])[cliente_col].nunique().reset_index()

    # Pivotar los datos (los meses faltantes quedarán automáticamente como NaN)
    pivot = cohorte_counts.pivot(index='cohorte', columns='mes_cohorte', values=cliente_col)

    # 4. Convertir conteos en tasas de retención (dividiendo por el mes 0)
    cohort_size = pivot[0]
    pivot_retention = pivot.divide(cohort_size, axis=0)

    # 5. Formatear nombres de columnas e índice según requisitos específicos
    pivot_retention.columns = [f'mes_{int(col)}' for col in pivot_retention.columns]
    pivot_retention.index.name = 'cohorte'

    return pivot_retention